name: AL
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.9.24=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - python=3.8.20=he870216_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - cmake==3.31.0.1
      - easydict==1.13
      - filelock==3.16.1
      - fsspec==2024.10.0
      - huggingface-hub==0.26.2
      - idna==3.10
      - jinja2==3.1.4
      - lit==18.1.8
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - packaging==24.2
      - pillow==10.4.0
      - pyyaml==6.0.2
      - requests==2.32.3
      - scipy==1.10.1
      - sympy==1.13.3
      - timm==0.6.12
      - torch==2.0.1
      - torchvision==0.15.2
      - tqdm==4.67.0
      - triton==2.0.0
      - typing-extensions==4.12.2
      - urllib3==2.2.3
prefix: /root/autodl-tmp/jww/miniconda3/envs/AL
